version: '3'

services:
  backend:
    env_file:
      - ./env/prod.env
    image: registry.gitlab.propulsion-home.ch/natayra-santos/week-7/day-3-gitlab-and-deployment:master
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      - frontend:/frontend/build
    command: 'sh /scripts/run.sh'
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/prod.env
    volumes:
      - postgres_db:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static-files
      - media-files:/media-files
      - frontend:/frontend
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgres_db:
  static-files:
  media-files:
  frontend:
