version: '3'

services:
  app:
    image: registry.gitlab.propulsion-home.ch/natayra-santos/week-7/day-3-gitlab-and-deployment:master
    env_file:
      - ./env/dev.env
    ports:
      - '9000:8000'
    volumes:
      - ./backend:/backend
    command: 'python manage.py runserver 0:8000'
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/dev.env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_db:
