name: django_motion

dependencies:
  - python=3.7.6
  - psycopg2
  - pip:
      - Pillow==7.1.2
      - flake8
      - django==3.0.7
      - djangorestframework==3.11.0
      - djangorestframework-simplejwt==4.4.0
      - django-rest-registration==0.5.6
      - coreapi==2.3.3
      - markdown==3.2.2
      - gunicorn==20.0.4
